language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: script
  skip_cleanup: true
  script: "./gradlew publish -Dorg.gradle.internal.publish.checksums.insecure=true"
  on:
    all_branches: true
#env:
#  global:
